### ISSUE TITLE
Bug: Graph legend square not square

### ISSUE THREAD

**Issue by Majorfi** [yearn/b2b-dashboard#146]
### What happened 🆘
Minor UI issue on the `Aggregate Wrapper Balance (USD)` graph, the Square for the `Aggregate Wrapper Balance` legend is not a square. Should be square. 

### To Reproduce 🔂
Steps to reproduce the behavior: Visit a partner page and check the rectangle.

### More 🔎
- Browser: All
- Screen size: 13'

## Screenshots
<img width="1295" alt="Capture d’écran 2023-03-17 à 12 10 30" src="https://user-images.githubusercontent.com/90963895/225888868-55c8480b-936d-4902-9d9d-e9e91ddef87b.png">

**Comment by 0xMirim** [comment]
Good eye! Technically I implemented it this way because this is how it's specified in the Figma design. I will consult Lord Kox to see how important the rectangle is.

<img width="695" alt="design" src="https://user-images.githubusercontent.com/95051992/225921519-c99c6c29-a9df-41b7-8755-2ba19394e22a.png">
